python experimental/ddpo_finetune.py \
    --reward_model_name "clipscore_v2" \
    --prompt_file "finetune_datasets/test_prompts.txt" \
    --num_epochs=100 \
    --train_gradient_accumulation_steps=1 \
    --sample_num_steps=50 \
    --sample_batch_size=8 \
    --train_batch_size=4 \
    --sample_num_batches_per_epoch=4 \
    --per_prompt_stat_tracking=True \
    --per_prompt_stat_tracking_buffer_size=32 \
    --tracker_project_name="stable_diffusion_training" \
    --log_with="wandb" \
    --use_lora=True